Спринт_5
whoisbulat/Sprint_5 pull request #1
Opened 2023-10-11 20:06 UTC by whoisbulat

Тесты на проект - https://stellarburgers.nomoreparties.site/

2023-10-15 08:58 UTC, kadirovgm requested changes

2023-10-15 08:58 UTC, kadirovgm commented on README.MD
> -
Хорошее reademe!

2023-10-15 08:58 UTC, kadirovgm commented on conftest.py
Можно лучше: ты уже мержил PR-ы до того, как отправить мне на ревью, так не нужно делать, любой PR здесь и на реальных проектах должен проходить ревью, только по этому он может быть вмержен в основную ветку (master). 

Из-за этого я буду оставлять комменты не в тех местах, где стоит править..

Можно лучше: на 13-ой строке install не обязателен, даже лучше его убрать, так как код должен быть универсален

Вот пример простой фикстуры, которая позволяет setup и teardown для тестовых методов

```
@pytest.fixture()
def driver():
    driver = webdriver.Chrome()
    driver.get(<url main page>)

    yield driver
    driver.quit()
```

2023-10-15 08:58 UTC, kadirovgm commented on conftest.py
Можно лучше: на 16-ой строке
тестовые статичные данные лучше выносить в отдельный файл типа [data.py](http://data.py/) или [urls.py](http://urls.py/)
Это нужно для легкой поддержке проекта и переиспользовании тестовых данных, мы должны стремиться к тому, чтобы разделять код и тестовые данные, тем самым избегая повторений.

2023-10-15 08:58 UTC, kadirovgm commented on conftest.py
>  def login(driver):
отлично! хорошая фикстура, только тестовые данные - креды пользователя также лучше выносить в отдельный файл, data.py и сгруппировать в отдельный класс, например, UserCredits() И так далее

2023-10-15 08:58 UTC, kadirovgm commented on locators/locators.py
> -
Отлично! хорошие локаторы

Можно лучше: на 3-ей строке
- класс с локаторами лучше разделить на несколько: например `AuthPageLocators`, `MainPageLocators`
Сейчас это не критично, но в будущем это точно стоит сделать, так как таким образом ты не будешь импортить лишние локаторы в файл с тестами на экран авторизации. Т.е. у каждой страницы должен быть свой класс с локаторами.
    
При таком подходе код станет лаконичнее, легко поддерживаемой. Ведь у экрана авторизации и у экрана главной могут быть свои NEXT_BUTTON например. Тогда можно будет легко оба обозвать именно так:
    `MainPageLocators.NEXT_BUTTON` и `AuthPageLocators.NEXT_BUTTON`

2023-10-15 08:58 UTC, kadirovgm commented on tests/test login.py
>          driver = login
Можно лучше: 11 строка и ниже
Гарантирует ли текст 'Соберите бургер' то, что пользователь авторизован, может как то более явно можно в этом убедиться?

2023-10-15 08:58 UTC, kadirovgm commented on tests/test login.py
>          driver = login
Можно лучше: ты каждый раз обращаешься к одним и тем же кредам пользователя, как писал выше их лучше вынести в отдельный класс и переиспользовать

2023-10-15 08:58 UTC, kadirovgm commented on tests/test logout from account.py
>  class TestLogout:
хороший тест!

2023-10-15 08:58 UTC, kadirovgm commented on tests/test personal account navigation.py
>              driver = login
нужно исправить: все локаторы стоит держать в одном месте, в твоем случае в locators.py

2023-10-15 08:58 UTC, kadirovgm commented on tests/test personal account to constructor transition.py
>          assert text == 'Соберите бургер'
можно лучше: 8-ая строка
Не оптимальнее здесь пользоваться фикстурой login?

2023-10-15 08:58 UTC, kadirovgm commented on tests/test_registration.py
>          email = faker.email()
нужно исправить: 18-ая строка: давай добавим более явную проверку, которая гарантирует, что тест успешен - регистрация успешна, проверка URL ни о чем тут не говорит

2023-10-15 08:58 UTC, kadirovgm commented on tests/test_registration.py
>          email = faker.email()
можно лучше: ко всем ассертам стоит добавить assert messages, чтобы при падении теста была более конкретная инфа в отчете

2023-10-21 21:28 UTC, whoisbulat commented on tests/test personal account navigation.py
>              driver = login
Благодарю за подробные комменты.  Все обязательные исправления тут https://github.com/whoisbulat/Sprint_5/pull/1/commits/265f93d103b79ffbecde9092b9b403ed273d5b55 
В файле убрал локаторы

2023-10-21 21:29 UTC, whoisbulat commented on tests/test_registration.py
>          email = faker.email()
Изменил тест.  Сделал явную проверку - 
```
        text = WebDriverWait(driver, 10).until(EC.visibility_of_element_located(
            (locators.FORGOT_PASSWORD_LINK))).text
        assert text == 'Восстановить пароль'
```

2023-10-22 21:36 UTC, kadirovgm approved these changes

2024-01-04 12:28 UTC, merged